version: '3'
services:
  nifi:
    image: 'apache/nifi:latest'
    container_name: nifi
    ports:
      - '8080:8080'
    environment:
      NIFI_WEB_HTTPS_PORT: '8080'
    volumes:
      - 'sender:/opt/nifi/sender'
      - 'receive:/opt/nifi/receive'
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.3.2'
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: 'confluentinc/cp-kafka:7.3.2'
    container_name: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  spark:
    container_name: spark
    image: 'docker.io/bitnami/spark:3.3'
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '9090:9090'
  spark-worker:
    container_name: spark-worker
    image: 'docker.io/bitnami/spark:3.3'
    environment:
      - SPARK_MODE=worker
      - 'SPARK_MASTER_URL=spark://spark:7077'
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark
    volumes:
      - 'sender:/opt/nifi/sender'
      - 'receive:/opt/nifi/receive'
volumes:
  sender:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:\Users\FabrizioFerla\Desktop\Nuova cartella\Nifi-Kafka-Spark\sender'
  receive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:\Users\FabrizioFerla\Desktop\Nuova cartella\Nifi-Kafka-Spark\receive'
