version: '3'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTPS_PORT: "8080"
    volumes:
      - sender:/opt/nifi/sender
      - recive:/opt/nifi/recive

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
volumes:
  sender:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/fabrizioferla/desktop/sender
  recive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/fabrizioferla/desktop/recive
