#==========================================================
#= Articoli Web Service - Autenticazione OAUTH2 keycloak
#==========================================================
server:
  port: 5051
  
spring:
  application:
    name: ArticoliWebService
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/Alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG
    
# ==============================================================
# = Parametri Sicurezza OAUTH2 con KeyCloack 
# ==============================================================
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: Alphashop
  resource: ArticoliWebService
  public-client: true 
  
  
  